# Generated by Django 5.0 on 2023-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
