# Generated by Django 5.0 on 2024-01-03 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_register_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('cimage', models.ImageField(null=True, upload_to='customer_images')),
                ('gender', models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male'), ('other', 'other')], max_length=10)),
                ('housename', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=6)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('Ph', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male'), ('other', 'other')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
