# Generated by Django 5.0 on 2024-01-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_staff_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='email',
            new_name='staff_email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Gender',
            new_name='staff_gender',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='staff_name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Ph',
            new_name='staff_ph',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='status',
            new_name='staff_status',
        ),
        migrations.AddField(
            model_name='staff',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_house_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_street',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
