# Generated by Django 5.0 on 2024-01-12 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_rename_email_staff_staff_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('catimage', models.ImageField(null=True, upload_to='category_images')),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('proimage', models.ImageField(null=True, upload_to='product_images')),
                ('gender', models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male'), ('other', 'other')], max_length=10)),
                ('size', models.CharField(max_length=5)),
                ('clothmate', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subimage', models.ImageField(null=True, upload_to='subcategory_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.category')),
            ],
        ),
    ]
