# Generated by Django 5.0 on 2024-01-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_category_sell_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sell',
            new_name='Seller_Product',
        ),
    ]
