# Generated by Django 5.0 on 2024-01-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_rename_sell_seller_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='color',
            field=models.CharField(default='', max_length=30),
        ),
    ]
