# Generated by Django 5.0 on 2024-01-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_seller_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
