# Generated by Django 5.0 on 2024-01-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_customer_is_customer_customer_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
    ]
