# Generated by Django 5.0 on 2024-01-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_remove_customer_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.customer'),
        ),
        migrations.AddField(
            model_name='seller_product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.subcategory'),
        ),
    ]
