# Generated by Django 5.0 on 2024-01-13 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_seller_product_seller_seller_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_product',
            old_name='clothmate',
            new_name='cloth_Material',
        ),
        migrations.RenameField(
            model_name='seller_product',
            old_name='proimage',
            new_name='product_Image',
        ),
        migrations.AddField(
            model_name='seller_product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='gender',
            field=models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_gender',
            field=models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], max_length=10),
        ),
    ]
