# Generated by Django 5.0 on 2024-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_alter_customer_district_alter_seller_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
