# Generated by Django 5.0 on 2024-02-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_remove_customer_city_remove_customer_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
