# Generated by Django 5.0 on 2024-02-07 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_remove_customerdetails_is_seller_customer_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.customer'),
        ),
    ]
