# Generated by Django 5.0 on 2024-02-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_remove_customerdetails_user_customerdetails_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
