# Generated by Django 5.0 on 2024-02-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_seller_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender_sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gendersubimage', models.ImageField(null=True, upload_to='gender_sub_category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='seller_product',
            name='gender_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.gender_sub_category'),
        ),
    ]
