# Generated by Django 5.0 on 2024-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_remove_seller_product_gender_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
