# Generated by Django 5.0 on 2024-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='profit_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
