# Generated by Django 4.0 on 2024-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_alter_cart_profit_amount_alter_cart_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(max_length=16)),
                ('cvv', models.IntegerField(max_length=3)),
            ],
        ),
    ]
