# Generated by Django 4.0 on 2024-03-04 17:10

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0025_alter_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expdate',
            field=month.models.MonthField(help_text='Enter month and year only', null=True, verbose_name='Month Value'),
        ),
    ]
