# Generated by Django 4.0 on 2024-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0029_cart_delivered_cart_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seller_amount',
            field=models.FloatField(null=True),
        ),
    ]
