# Generated by Django 4.0 on 2024-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0030_cart_seller_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
