# Generated by Django 4.0 on 2024-03-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0031_alter_cart_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
