# Generated by Django 4.0 on 2024-03-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0032_seller_product_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pay', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.cart')),
                ('products', models.ManyToManyField(to='demo.Seller_Product')),
            ],
        ),
    ]
