# Generated by Django 4.0 on 2024-03-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0035_remove_order_cart_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='demo.Seller_Product'),
        ),
    ]
