# Generated by Django 4.0 on 2024-03-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('demo', '0037_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pay', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='demo.Seller_Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
