# Generated by Django 4.0 on 2024-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0039_courier_courier_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier_assign',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier_assign',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
