# Generated by Django 4.0 on 2024-03-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0040_courier_assign_completed_courier_assign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier_assign',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
